### ISSUE TITLE
Small guide to retrieve the style?

### ISSUE THREAD

**Issue by spolo96** [holy-crusader-py/wombopy#7]
First of all, thanks a lot for this module! It's really nice given the fact that unfortunately Wombo doesn't have an automatic way to download its images...

I already have seen the other issues but I'm able to retrieve the _style id_ in order to use it in the CLI to properly get an image. Would you please give me some hints, maybe a small screenshot to see how can I retrieve it?

P.D: Thanks a lot!

**Comment by holy-crusader-py** [comment]
Hi, thank you very much for your message!
I'll try to make a script to get all the styles but in the meantime here's a screenshot that shows how to do it (it's a bit long)!

![image](https://github.com/holy-crusader-py/wombopy/assets/67459553/4d2bea52-f0bd-4360-8f85-e0527a320e88)

If you have any other question don't hesitate

**Comment by spolo96** [comment]
Thanks a lot for your quick response @holy-crusader-py ! 

With your help, I was able to retrieve the style I want, however, when I try to execute the following code snippet from #3 with my key, it doesn't work:

> ```python
> from wombopy import create, identify
> token = identify("AIzbS5DCvp7MTJMUdtBYELYWXJrlLuKM6Xw")["id_token"]
> image_url = create(token, "death", 3)
> print(image_url)
> ```

After replacing the previous values with my key and my prompt, this is what I get:

![imagen](https://github.com/holy-crusader-py/wombopy/assets/14812150/1e9f37ae-fa24-4714-94ab-ff0fea37f21a)

I also tried to use this via CLI, I replaced [my_key] with my key using your help and I get the same error:

![imagen](https://github.com/holy-crusader-py/wombopy/assets/14812150/032504a9-9226-427c-a905-5eb76d061076)

Thanks a lot again for your quick response!

**Comment by holy-crusader-py** [comment]
Ok, I'll fix It when I can
Btw, I've written a script that can retrieve style ids!

**Comment by holy-crusader-py** [comment]
Here is the dictionary with style names and ids

```py
{'Buliojourney v2': 84, 'Realistic v2': 78, 'Horror v2': 103, 'Horror Cut v2.0': 104, 'Horror Cut v2.1': 105, 'Poster Art': 105, 'Mystical': 11, 'Dark Fantasy': 10, 'Vibrant': 6, 'Toasty': 31, 'Ink v2': 100, 'Dreamwave v2': 100, 'The Bulio Cut': 97, 'The Cut': 95, 'Gloomy': 94, 'Spectral v2': 92, 'Anime v2': 80, 'Flora v2': 81, 'Watercolor v2': 91, 'Blues v2': 88, 'Expressionism v2': 83, 'Expressionism': 77, 'Figure': 77, 'HDR': 52, 'Spectral': 63, 'Comic': 45, 'Splatter': 74, 'Winter': 72, 'Festive': 12, 'Soft Touch': 71, 'Realistic': 32, 'Flora': 68, 'Abstract': 67, 'Diorama': 65, 'Fantastical': 61, 'Vector': 60, 'Cartoonist': 58, 'Bad Trip': 57, 'Isometric': 55, 'Retro-Futurism': 54, 'Analogue': 53, 'Paint': 50, 'Polygon': 49, 'Gouache': 49, 'Ink': 38, 'Line-Art': 47, 'Anime': 46, 'Malevolent': 40, 'Surreal': 37, 'Unrealistic': 42, 'Throwback': 35, 'Street Art': 41, 'No Style': 3, 'Ghibli': 22, 'Melancholic': 28, 'Pandora': 39, 'Daydream': 36, 'Provenance': 17, 'Arcane': 34, 'Rose Gold': 18, 'Wuhtercuhler': 16, 'Etching': 14, 'Psychic': 9, 'HD': 9, 'Steampunk': 4, 'Fantasy Art': 5, 'Synthwave': 1, 'Ukiyoe': 2}
```

and the messy code to get it => https://gist.github.com/holy-crusader-py/71370201f724a1f4fbf0d7f2f89823d7
